version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: users_container
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app-users
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
