export default {
  rootDir: './',
  collectCoverageFrom: ['**/*.ts'],
  coverageDirectory: './coverage',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '/.yalc/',
    '/dist/',
    'jest.config.ts',
    'src/main.ts',
    'src/shared/',
    '^.*\\.module\\.[jt]s?$',
    '^.*\\.config\\.[jt]s?$',
    '^.*\\.migration\\.[jt]s?$',
    '^.*\\.dto\\.[jt]s?$',
    '^.*\\index\\.[jt]s?$',
    '^.*\\.entity\\.[jt]s?$',
  ],
  testMatch: ['**/*.spec.ts'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  moduleDirectories: ['node_modules', 'src'],
  moduleFileExtensions: ['js', 'json', 'ts'],
  testEnvironment: 'node',
  //testResultsProcessor: 'jest-sonar-reporter',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  //setupFiles: ['./jest.setup.ts'],
  silent: true,
  verbose: false,
};
